// File generated by FlutterFire CLI.
// Run: dart pub global activate flutterfire_cli
//      flutterfire configure
//
// Replace this placeholder after configuring your Firebase project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhKTHzzytx9c0-F1AFejdm_-w1CCe6VFk',
    appId: '1:702832148898:web:f0d82a6711f52dc00eb2fb',
    messagingSenderId: '702832148898',
    projectId: 'scripture-memorizer-app',
    authDomain: 'scripture-memorizer-app.firebaseapp.com',
    storageBucket: 'scripture-memorizer-app.firebasestorage.app',
    measurementId: 'G-3LH2RJZ9C0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMvRZ_YyLCOsHKHv66LAE0gyJ5XOm7t00',
    appId: '1:702832148898:android:c6945b34bddcd6c50eb2fb',
    messagingSenderId: '702832148898',
    projectId: 'scripture-memorizer-app',
    storageBucket: 'scripture-memorizer-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdlPW570eSTnv4lr-mN2qWTeLOBdk77Hc',
    appId: '1:702832148898:ios:445b4142777cceac0eb2fb',
    messagingSenderId: '702832148898',
    projectId: 'scripture-memorizer-app',
    storageBucket: 'scripture-memorizer-app.firebasestorage.app',
    iosBundleId: 'com.scripturememorizer.scriptureMemorizer',
  );

  static const FirebaseOptions macos = ios;

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhKTHzzytx9c0-F1AFejdm_-w1CCe6VFk',
    appId: '1:702832148898:web:cf64c89c9e4b8c5c0eb2fb',
    messagingSenderId: '702832148898',
    projectId: 'scripture-memorizer-app',
    authDomain: 'scripture-memorizer-app.firebaseapp.com',
    storageBucket: 'scripture-memorizer-app.firebasestorage.app',
    measurementId: 'G-T8NP9MZ2MS',
  );

}